### ISSUE TITLE
syntax highlight for fenced code block

### ISSUE THREAD

**Issue by rkarsnk** [tosi29/inkblotty#7]
\`\`\`　\`\`\` で囲まれたコードブロックにGitHub風のsyntax highlightを適用するように、こちらで変更しました。

適用する`syntax.css`は以下のコマンドで生成しています。
``` bash
hugo gen chromastyles --style=github > syntax.css
```

head.htmlで上記の`syntax.css`を読み込み、
config.tomlに以下の記述を追加することで、syntax highlightが適用されます。

``` toml
pygmentsUseClasses = true
pygmentsCodefences = true
```
プルリクも出しますね。 #8
